### ISSUE TITLE
[Refactor] 함께배달 게시글 페이지 리팩토링

### ISSUE THREAD

**Issue by EungBug** [FC-Chilli-Bubble/front-officener#103]
### 📌 Description

함께배달 글 등록, 수정 페이지 리팩토링

### ✅ ToDo

- [ ] 모바일 UI 이슈 해결 - 키보드 영역처리 등
- [ ] Input 요소 처리 (, 적용)
- [ ] 메뉴판 링크 URL 유효성 검사 처리
