### ISSUE TITLE
[Refactor] 채팅 리팩토링 진행

### ISSUE THREAD

**Issue by doitidey** [FC-Chilli-Bubble/front-officener#107]
### 📌 Description

채팅 기능 관련 리팩토링을 진행합니다.

### 📝 ToDo

 - [ ] chat bubble 관련 로직 재설계
   input과 화면, header의 상하 관계를 재설계하여 input focus시 **scrolling 되는 부분을 조금 더 자연스럽게** 할 수 있을 거라고 예상됩니다.

 - [ ] header 부분에서 복사 클릭 시 인터랙션 ui 추가
   복사 버튼을 누르고 나서 아무런 반응 설계가 되어있지 않아, 사용자 입장에서 불편함이 있을 것 같아 **인터랙션하는 ui를 추가**해보고자 합니다.

 - [ ] 웹소켓 연결 불안정 이슈 파악 후 재설계
   useEffect의 return을 이용하여, 컴포넌트가 언마운트 될 때 웹소켓 연결을 해제 시키는 로직으로 구현하였습니다. 다만 이 부분이 잘 작동하지 않는 것으로 파악되었고, **채팅방을 나갈 때 웹소켓 연결이 제대로 해제되지 않아 채팅방 재접속시 웹소켓 연결이 원활히 이뤄지지 않는 것**으로 문제점을 파악했습니다. (아직까지는...) 이를 해결해보고자 합니다.
