### ISSUE TITLE
[Feat] 회원가입 UI작업

### ISSUE THREAD

**Issue by kse-seong-eun** [FC-Chilli-Bubble/front-officener#15]
### 📌 Description
회원가입 영역 UI 작업
라우터 분리 : 
- 인트로, 
- 사용자 동의 + 빌딩찾기 + 회사 찾기 + 회원가입 + 휴대폰본인인증 + 입주자 카드

### 📝 ToDo

 - [x] todo 1 인트로 UI작업
 - [x] todo 2 사용자 동의 UI작업
 - [x] todo 3 빌딩/오피스 UI작업
 - [x] todo 4 회원가입/휴대폰본인인증 UI작업
 - [x] todo 5 입주자 카드 UI작업
