### ISSUE TITLE
[Feat] 알림 화면 UI

### ISSUE THREAD

**Issue by EungBug** [FC-Chilli-Bubble/front-officener#19]
### 📌 Description

알림 페이지 UI 작업 

### 📝 ToDo

 - [x] 새로운 알림 목록
 - [x] 지난 알림 목록
 - [x] 알림 읽음 버튼
