### ISSUE TITLE
[Bug] 공통 UI 이슈

### ISSUE THREAD

**Issue by EungBug** [FC-Chilli-Bubble/front-officener#33]
### 📌 Description

- BottomNavigation 패딩 필요
- BottomSheet 폰트 적용 필요
- 프로필 이미지 깨짐 현상
- BottomNavigation 색상 수정 필요

### ✅ ToDo

- [x] BottomNavigation 아이콘 파일 수정
- [x] BottomNavigation 패딩 조절
- [x] 글로벌 스타일에서 폰트 우선순위 적용
- [x] 프로필 이미지 파일 수정 
- [x] BottomSheet 닫기 수정 필요
