### ISSUE TITLE
[Bug] 채팅 UI 수정

### ISSUE THREAD

**Issue by doitidey** [FC-Chilli-Bubble/front-officener#35]
### 📌 Description

- 참여 마감 모달 줄바꿈 처리가 필요
- 신고 바텀시트 중 인풋 박스 클릭 시 키보드가 올라오면서 바텀시트가 가려짐
- 모바일 화면에서 복사, 전송 아이콘 잘림 현상 있음
- 채팅 입력시 키보드 올라오면 헤더 사라짐 
- guest 버튼 아이콘 누락

### ✅ ToDo

- [x] 모달 줄바꿈 처리 후 모달 컴포넌트에 전송 
- [x] 바텀시트 확인
- [x] 아이콘 위치 확인
- [x] 헤더 수정
- [x] guest 버튼 아이콘 같이 넘기기 (버튼 props 타입 재지정)
- [x] 신고 바텀시트 컴포넌트 명 수정 (숫자 사용 지양)
