### ISSUE TITLE
[Bug] 함께배달 UI 수정

### ISSUE THREAD

**Issue by dhmoon11** [FC-Chilli-Bubble/front-officener#36]
### 📌 Description

- 글쓰기 버튼 누락
- 뒤로가기 버튼 누락
- 리스트 가로 스크롤 숨김처리 (pc)
- 주문리스트 태그 간격 수정
- 메인페이지 스크롤시 메뉴  탭 상단 영역 고정
- 디테일페이지 간격 수정
- 네비게이션 간격, 크기 수정
- 헤더 사진 누락(렌더링문제)

### ✅ ToDo

- [x] 글쓰기 버튼 추가
- [x] 뒤로가기 버튼 추가
- [ ] 스크롤 숨김처리
- [x] 메뉴  탭 상단 영역 고정
- [x] 주문리스트, 디테일페이지, 네비게이션 간격, 크기 수정
- [x] 헤더 사진 렌더링문제 해결

- 글쓰기 버튼(postbutton) 및 상단 헤더(StyledHeader) 부분의 백그라운드 이미지가 특정 액션을 취했을 때 사라지는 현상 ,
