### ISSUE TITLE
[Feat] 회원가입 빌딩&오피스 찾기 및 선택

### ISSUE THREAD

**Issue by kse-seong-eun** [FC-Chilli-Bubble/front-officener#51]
### 📌 Description

SignupStep 2, Step3
건물 검색 기능과 선택, 오피스 선택과 기능 선택 기능 추가
+ API 연동

### 📝 ToDo

 - [x] 건물 찾기 API연동
 - [x]  건물찾기 및 선택 로직 구현
 - [x] 선택된 [빌딩이름, 오피스이름] 리코일로 저장하기
