### ISSUE TITLE
[Feat] 함께배달 상세화면 기능 연동

### ISSUE THREAD

**Issue by EungBug** [FC-Chilli-Bubble/front-officener#60]
### 📌 Description

함께배달 게시글 상세조회 API 연동

### 📝 ToDo

 - [x] 게시글 상세조회 API 연동
 - [x] 게시글 조회 데이터 컴포넌트 연결
 - [x] 예외처리 추가
 - [x] 수정/삭제 버튼 함수 연동
