### ISSUE TITLE
[Feat] 엘리베이터 전체 목록 조회 및 엘리베이터 설정 

### ISSUE THREAD

**Issue by EungBug** [FC-Chilli-Bubble/front-officener#77]
### 📌 Description

수정된 엘리베이터 api 연동

### 📝 ToDo

 - [x] 엘리베이터 전체 목록 조회 API 연동
 - [x] 설정된 엘리베이터 목록 조회 API 연동
 - [x] 엘리베이터 설정 API 연동

**Comment by EungBug** [comment]
엘리베이터 카드 로딩 ui 추가 필요
