### ISSUE TITLE
[Bug] 채팅룸 UI, 헤더 API 연결 놓침 이슈

### ISSUE THREAD

**Issue by doitidey** [FC-Chilli-Bubble/front-officener#93]
### 📌 Description

- UI 문제
  - 채팅 데이터를 거꾸로 배열하면서 프로필 위치, 채팅 버블 간격 등이 어긋남
- api 연결 놓침
  - 채팅 헤더 더미데이터 부분 api 연결 필요

### ✅ ToDo

버그 수정을 위한 ToDoList를 작성해주세요.

- [x] 프로필 추가 로직 수정
- [x] 간격 로직 수정
- [x] api 불러오기 후 뿌려주기
